Fix Region Brick (and menu refactoring)
GaryOderNichts/recovery_menu pull request #11
Opened 2022-08-18 00:55 UTC by GerbilSoft

This PR has two major changes:

1. Refactoring of the menu system to reduce flickering and improve code reuse.
2. "Fix Region Brick" option. This option compares productArea and gameRegion against installed Wii U Menus. If a Wii U Menu that matches productArea can't be found, then others are searched for. If one is found, the user will have the opportunity to change the productArea and gameRegion values to match the installed Wii U Menu.

Here's my CAT-DEV with productArea = KOR and gameRegion = TWN:
![LG_Smart_TV 2022-08-17 20-50-03](https://user-images.githubusercontent.com/6764716/185268806-222d73e5-e6eb-4b6b-9765-c2ab9c1127ed.jpg)

The system has a USA Wii U Menu installed, so let's fix it by setting the region to USA:
![LG_Smart_TV 2022-08-17 20-50-09](https://user-images.githubusercontent.com/6764716/185268869-956a3df0-9f39-4c38-b652-4342b6ab2b6f.jpg)

And verify by re-opening the "Fix Region Brick" menu afterwards:
![LG_Smart_TV 2022-08-17 20-50-13](https://user-images.githubusercontent.com/6764716/185268839-ed921bce-3274-4093-a266-6627339dc727.jpg)

2022-08-18 14:02 UTC, GaryOderNichts requested changes
Nice addition overall, thanks for this.

Not completely happy with the menu system yet, but this is already an improvement. I plan on rewriting and cleaning up some of this in the future anyways.

2022-08-18 22:22 UTC, GerbilSoft commented on ios_mcp/source/menu.c
> +    {"Fix Region Brick",            {.callback = option_FixRegionBrick}},
I think "Fix Region Brick" is a more obvious description for the end user. "Verify" implies that it only checks the region, whereas "Fix" implies it'll fix it.

2022-08-18 22:22 UTC, GerbilSoft commented on ios_mcp/source/menu.c
> +    gfx_printf(16, index, 0, "Repair the system by setting the region code to %s?", menu_region_str);
Changed the menu option to "Fix Region" and left this string as-is.

2022-08-19 04:00 UTC, vaguerant commented on ios_mcp/source/menu.c
> +    {"Fix Region Brick",            {.callback = option_FixRegionBrick}},
`Debug System Region` might thread the needle of both "Verify" and "Fix"?

2022-08-19 07:00 UTC, GerbilSoft commented on ios_mcp/source/menu.c
> +    {"Fix Region Brick",            {.callback = option_FixRegionBrick}},
That could work.

2022-08-19 09:52 UTC, merged